// ╔══════════════════════════════════════════════════════════════════╗
// ║              RIFATH'S PORTFOLIO — PAGE ENGINE                    ║
// ║                                                                  ║
// ║  ⚠️  DO NOT EDIT THIS FILE.                                       ║
// ║  All your content lives in  js/content.js  — edit that instead.  ║
// ║                                                                  ║
// ║  What this file does:                                            ║
// ║  It reads everything from content.js and builds the whole page.  ║
// ║  Think of content.js as the recipe, and this file as the oven.   ║
// ╚══════════════════════════════════════════════════════════════════╝


// ── WAIT UNTIL THE PAGE IS FULLY LOADED BEFORE DOING ANYTHING ──────────────
// "DOMContentLoaded" fires when the HTML is ready but images haven't loaded.
// We wait for this so we can safely find elements on the page by their IDs.
document.addEventListener('DOMContentLoaded', () => {


  // ════════════════════════════════════════════════════════════════
  //  NAV BAR — adds a shadow when you scroll down
  // ════════════════════════════════════════════════════════════════

  const nav = document.querySelector('nav');

  // Every time the user scrolls, check if they've gone more than 30px down.
  // If yes → add the "scrolled" class (which adds a box-shadow in CSS).
  // If no  → remove it.
  window.addEventListener('scroll', () => {
    nav.classList.toggle('scrolled', window.scrollY > 30);
  });


  // ════════════════════════════════════════════════════════════════
  //  NAV LOGO — fills in your name from content.js
  // ════════════════════════════════════════════════════════════════

  // SITE.name comes from js/content.js → name: "Md Rifath Ahamed"
  document.querySelector('.nav-logo').textContent = SITE.name;


  // ════════════════════════════════════════════════════════════════
  //  HERO HEADING — renders the big name at the top of the page
  // ════════════════════════════════════════════════════════════════

  const heroH1 = document.getElementById('hero-h1');

  // heroHeading in content.js uses \n to mean "new line".
  // We split on \n to get an array of lines:
  // "Md Rifath\nAhamed." → ["Md Rifath", "Ahamed."]
  const lines = SITE.heroHeading.split('\n');

  // Build the HTML for the heading.
  // Every line except the last gets a <br> (line break).
  // The LAST line: its last word gets wrapped in <span class="accent">
  // so CSS can colour it amber.
  heroH1.innerHTML = lines.map((line, i) => {
    const isLastLine = (i === lines.length - 1);

    if (!isLastLine) {
      // Not the last line — just add a line break after it
      return line + '<br>';
    }

    // Last line: colour the last word
    const words = line.split(' ');
    if (words.length > 1) {
      // e.g. "Md Ahamed." → "Md <span class='accent'>Ahamed.</span>"
      const allButLast = words.slice(0, -1).join(' ');
      const lastWord   = words[words.length - 1];
      return allButLast + ' <span class="accent">' + lastWord + '</span>';
    }

    // If the last line is just one word, colour the whole thing
    return '<span class="accent">' + line + '</span>';
  }).join('');


  // ════════════════════════════════════════════════════════════════
  //  HERO TAGLINE & DESCRIPTION
  // ════════════════════════════════════════════════════════════════

  // These just drop the text from content.js into the right HTML elements.
  document.getElementById('hero-tagline').textContent = SITE.tagline;
  document.getElementById('hero-desc').textContent    = SITE.heroParagraph;


  // ════════════════════════════════════════════════════════════════
  //  HERO PHOTO
  //  Shows your photo if profilePhoto is set, otherwise shows initials.
  // ════════════════════════════════════════════════════════════════

  const photoWrap = document.getElementById('photo-content');

  if (SITE.profilePhoto) {
    // profilePhoto is set → show the image
    // e.g. SITE.profilePhoto = "images/profile.jpg"
    photoWrap.innerHTML = `<img src="${SITE.profilePhoto}" alt="${SITE.name}">`;

  } else {
    // profilePhoto is empty → show initials as a placeholder
    // Take first letter of each word in the name, use first 2 letters
    // e.g. "Md Rifath Ahamed" → "MR"
    const initials = SITE.name
      .split(' ')
      .map(word => word[0])
      .join('')
      .slice(0, 2)
      .toUpperCase();

    photoWrap.innerHTML = `
      <div class="photo-initials">
        <div class="initials">${initials}</div>
        <div class="hint">
          Add your photo:<br>
          1. Put  profile.jpg  in images/<br>
          2. Set profilePhoto in content.js
        </div>
      </div>`;
  }


  // ════════════════════════════════════════════════════════════════
  //  HERO FLOATING STAT BADGES
  //  The two little info cards that float on/near your photo.
  // ════════════════════════════════════════════════════════════════

  const s = SITE.stats; // shorthand — SITE.stats is the array in content.js

  // Badge 1 (bottom-left of photo): uses stats[0]
  // Badge 2 (top-right of photo):   uses stats[1]
  if (s.length >= 2) {
    document.getElementById('badge1-num').textContent   = s[0].num;
    document.getElementById('badge1-label').textContent = s[0].label;
    document.getElementById('badge2-num').textContent   = s[1].num;
    document.getElementById('badge2-label').textContent = s[1].label;
  }


  // ════════════════════════════════════════════════════════════════
  //  HERO "FULL PORTFOLIO" BUTTON
  //  Only shows if you've set googleDrivePortfolio in content.js.
  // ════════════════════════════════════════════════════════════════

  const driveBtn = document.getElementById('hero-drive-btn');
  if (SITE.googleDrivePortfolio) {
    driveBtn.href = SITE.googleDrivePortfolio;
    driveBtn.style.display = 'inline-flex'; // makes the button visible
  }
  // If googleDrivePortfolio is empty, the button stays hidden (display:none in HTML)


  // ════════════════════════════════════════════════════════════════
  //  ABOUT SECTION — paragraphs
  // ════════════════════════════════════════════════════════════════

  const aboutEl = document.getElementById('about-paragraphs');

  // SITE.about is an array of strings from content.js.
  // We wrap each string in a <p> tag and join them all together.
  // .map() transforms each item; .join('') glues them without separators.
  aboutEl.innerHTML = SITE.about
    .map(paragraph => `<p>${paragraph}</p>`)
    .join('');


  // ════════════════════════════════════════════════════════════════
  //  ABOUT SECTION — skill tags
  // ════════════════════════════════════════════════════════════════

  const skillsEl = document.getElementById('skills-wrap');

  // SITE.skills is an array of groups, each group has a name and tags array.
  // For each group: render its label, then render each tag as a <span>.
  skillsEl.innerHTML = SITE.skills.map(skillGroup => `
    <div class="skill-group">
      <div class="skill-group-label">${skillGroup.group}</div>
      <div class="skill-tags">
        ${skillGroup.tags.map(tag => `<span class="tag">${tag}</span>`).join('')}
      </div>
    </div>
  `).join('');


  // ════════════════════════════════════════════════════════════════
  //  PORTFOLIO GRID — the main photo/video section
  // ════════════════════════════════════════════════════════════════

  // Start by showing ALL portfolio items when the page first loads.
  buildPortfolio('all');

  // When a filter button is clicked (e.g. "Photography"):
  // 1. Remove the "active" highlight from ALL buttons
  // 2. Add the "active" highlight to the clicked button
  // 3. Rebuild the grid showing only items in that category
  document.querySelectorAll('.filter-btn').forEach(btn => {
    btn.addEventListener('click', () => {
      document.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));
      btn.classList.add('active');
      buildPortfolio(btn.dataset.cat); // data-cat is set in index.html on each button
    });
  });


  // ── buildPortfolio(category) ─────────────────────────────────────────────
  // This function clears the grid and refills it.
  // category = "all", "photography", "video", "social", or "science"
  function buildPortfolio(category) {
    const grid = document.getElementById('portfolio-grid');

    // Filter items: if category is "all" → use every item.
    // Otherwise → only items whose .category matches.
    const items = (category === 'all')
      ? SITE.portfolio
      : SITE.portfolio.filter(item => item.category === category);

    // Clear the grid — remove all existing cards
    grid.innerHTML = '';

    // If no items match, show a friendly message instead of a blank grid
    if (items.length === 0) {
      grid.innerHTML = `
        <p style="color:var(--text-light); font-style:italic; font-size:0.9rem; grid-column:1/-1; padding:2rem 0;">
          No items in this category yet.
          Add some in <strong>js/content.js</strong> → portfolio section.
        </p>`;
      return; // stop here, don't try to build cards
    }

    // Loop through each item and create the right kind of card
    items.forEach((item, index) => {

      // ── PHOTO CARD ──────────────────────────────────────────────
      // Shows a photo from your images/ folder.
      // Clicking it opens the photo fullscreen in a lightbox.
      if (item.type === 'photo') {
        const card = document.createElement('div');
        card.className = 'p-card reveal'; // "reveal" class = fade-in on scroll

        // Check if the image file exists by listening for an error.
        // If the file is missing → show a "missing" placeholder instead.
        card.innerHTML = `
          <img
            src="${item.src}"
            alt="${item.title}"
            loading="lazy"
            onerror="this.parentElement.classList.add('img-missing'); this.style.display='none';"
          >
          <div class="p-card-overlay">
            <div class="p-card-title">${item.title}</div>
            <div class="p-card-cat">${item.category}</div>
          </div>
          <div class="missing-label">Image not found:<br>${item.src}</div>
        `;

        // Click → open lightbox with this image
        card.addEventListener('click', () => {
          if (!card.classList.contains('img-missing')) {
            openLightbox('image', item.src, item.title);
          }
        });

        grid.appendChild(card);
      }

      // ── VIDEO CARD ──────────────────────────────────────────────
      // Shows a thumbnail image with a play button on top.
      // Clicking it opens the YouTube/Vimeo link in a new tab.
      else if (item.type === 'video') {
        const card = document.createElement('div');
        card.className = 'p-card reveal';

        // item.src is the thumbnail JPG. item.videoUrl is the YouTube link.
        const thumbHtml = item.src
          ? `<img src="${item.src}" alt="${item.title}" loading="lazy"
               onerror="this.style.display='none'">`
          : `<div class="video-no-thumb"></div>`; // grey box if no thumbnail

        card.innerHTML = `
          ${thumbHtml}
          <div class="play-btn" title="Watch video">▶</div>
          <div class="p-card-overlay">
            <div class="p-card-title">${item.title}</div>
            <div class="p-card-cat">Video</div>
          </div>
        `;

        // Click → open the YouTube/Vimeo URL in a new browser tab
        card.addEventListener('click', () => {
          if (item.videoUrl && !item.videoUrl.includes('PASTE_YOUR_VIDEO_ID_HERE')) {
            window.open(item.videoUrl, '_blank');
          } else {
            // videoUrl hasn't been filled in yet — show a friendly alert
            alert('Video URL not set yet. Open js/content.js and paste your YouTube link into videoUrl.');
          }
        });

        grid.appendChild(card);
      }

      // ── GOOGLE DRIVE CARD ────────────────────────────────────────
      // A card that links directly to a Google Drive folder.
      // Useful for showing a collection of work without uploading each file.
      else if (item.type === 'drive') {
        const card = document.createElement('a');
        card.className = 'p-placeholder reveal';
        card.href      = item.driveLink;
        card.target    = '_blank'; // opens in new tab
        card.innerHTML = `
          <div class="ph-num">↗</div>
          <div class="ph-title">${item.title}</div>
          <div class="ph-add">View on Google Drive</div>
        `;
        grid.appendChild(card);
      }

    }); // end forEach item


    // ── GOOGLE DRIVE BANNER (below the grid) ──────────────────────
    // The big "Browse full archive" banner under the portfolio grid.
    // Shows the Drive button only if googleDrivePortfolio is set.
    const driveCta    = document.getElementById('drive-cta');
    const driveCtaBtn = driveCta.querySelector('a');

    if (SITE.googleDrivePortfolio) {
      driveCtaBtn.href         = SITE.googleDrivePortfolio;
      driveCtaBtn.style.display = 'inline-flex'; // show the button
    } else {
      driveCtaBtn.style.display = 'none'; // hide the button if no link
    }

    driveCta.style.display = 'flex'; // always show the banner itself

    // Re-run the scroll reveal observer so new cards fade in properly
    observeReveal();

  } // end buildPortfolio()


  // ════════════════════════════════════════════════════════════════
  //  RESEARCH SECTION — the project cards
  // ════════════════════════════════════════════════════════════════

  const researchGrid = document.getElementById('research-grid');

  // SITE.research is an array of objects from content.js.
  // Each object has: type, title, org, desc.
  researchGrid.innerHTML = SITE.research.map(project => `
    <div class="r-card reveal">
      <div class="r-type">${project.type}</div>
      <div class="r-title">${project.title}</div>
      <div class="r-org">${project.org}</div>
      <div class="r-desc">${project.desc}</div>
    </div>
  `).join('');


  // ════════════════════════════════════════════════════════════════
  //  AWARDS SECTION
  // ════════════════════════════════════════════════════════════════

  const awardsEl = document.getElementById('awards-rows');

  awardsEl.innerHTML = SITE.awards.map(award => `
    <div class="award-item reveal">
      <div class="award-year">${award.year}</div>
      <div>
        <div class="award-title">${award.title}</div>
        <div class="award-detail">${award.detail}</div>
      </div>
    </div>
  `).join('');


  // ════════════════════════════════════════════════════════════════
  //  EXPERIENCE TIMELINE
  //  Two columns — Creative on left, Research on right.
  // ════════════════════════════════════════════════════════════════

  const expGrid = document.getElementById('exp-grid');

  // SITE.experience is an array of two "tracks" (columns).
  // Each track has a name and an array of timeline items.
  expGrid.innerHTML = SITE.experience.map(track => `
    <div>
      <div class="exp-track-label">${track.track}</div>
      <div class="timeline">
        ${track.items.map(job => `
          <div class="t-item reveal">
            <div class="t-date">${job.date}</div>
            <div class="t-role">${job.role}</div>
            <div class="t-org">${job.org}</div>
            <div class="t-desc">${job.desc}</div>
          </div>
        `).join('')}
      </div>
    </div>
  `).join('');


  // ════════════════════════════════════════════════════════════════
  //  CONTACT SECTION — links list
  // ════════════════════════════════════════════════════════════════

  const contactLinksEl = document.getElementById('contact-links');

  // Build an array of link objects, then filter out any that have no value.
  // This way, if facebookPage is "" it simply won't appear.
  const contactItems = [
    {
      href:  `mailto:${SITE.email}`,
      icon:  '✉',
      label: 'Email',
      val:   SITE.email,
      show:  !!SITE.email, // !! converts to true/false
    },
    {
      href:  `tel:${SITE.phone.replace(/\s/g, '')}`, // remove spaces for tel: link
      icon:  '📞',
      label: 'Phone',
      val:   SITE.phone,
      show:  !!SITE.phone,
    },
    {
      href:   SITE.linkedin,
      icon:   'in',
      label:  'LinkedIn',
      val:    'md-rifath-ahamed',
      target: '_blank',
      show:   !!SITE.linkedin,
    },
    {
      href:   SITE.facebookPage,
      icon:   'f',
      label:  'Facebook Page',
      val:    'Content & Portfolio Page',
      target: '_blank',
      show:   !!SITE.facebookPage, // only shows if facebookPage is filled in
    },
    {
      href:   SITE.googleDrivePortfolio,
      icon:   '▶',
      label:  'Portfolio Drive',
      val:    'Full content archive ↗',
      target: '_blank',
      show:   !!SITE.googleDrivePortfolio, // only shows if googleDrivePortfolio is filled in
    },
    {
      href:   SITE.portfolioUrl,
      icon:   '🌐',
      label:  'Website',
      val:    SITE.portfolioUrl,
      target: '_blank',
      show:   !!SITE.portfolioUrl, // only shows if portfolioUrl is filled in
    },
  ];

  // Render only the items where show: true
  contactLinksEl.innerHTML = contactItems
    .filter(item => item.show)
    .map(item => `
      <a href="${item.href}" class="c-link" ${item.target ? 'target="_blank"' : ''}>
        <div class="c-link-icon">${item.icon}</div>
        <div>
          <div class="c-link-label">${item.label}</div>
          <div class="c-link-val">${item.val}</div>
        </div>
      </a>
    `).join('');


  // ════════════════════════════════════════════════════════════════
  //  CV DOWNLOAD CARD
  //  Shows the "Download PDF" button only if cvPdfLink is set.
  // ════════════════════════════════════════════════════════════════

  const cvCard        = document.getElementById('cv-card');
  const cvBtn         = cvCard.querySelector('a.btn-warm');
  const cvHint        = cvCard.querySelector('.cv-hint');

  if (SITE.cvPdfLink) {
    // Link is set → show the download button, hide the hint
    cvBtn.href          = SITE.cvPdfLink;
    cvBtn.style.display = 'inline-flex';
    if (cvHint) cvHint.style.display = 'none';
  } else {
    // No link yet → hide the button, keep the hint visible
    cvBtn.style.display = 'none';
  }


  // ════════════════════════════════════════════════════════════════
  //  FOOTER — fills in your name
  // ════════════════════════════════════════════════════════════════

  document.getElementById('footer-name').textContent = SITE.name;


  // ════════════════════════════════════════════════════════════════
  //  LIGHTBOX — the fullscreen photo viewer
  //  Opens when you click a photo card.
  //  Closes when you click the X button or click outside the photo.
  // ════════════════════════════════════════════════════════════════

  const lightbox    = document.getElementById('lightbox');
  const lbImg       = document.getElementById('lb-img');
  const lbVideo     = document.getElementById('lb-video');
  const lbCaption   = document.getElementById('lb-caption');
  const lbCloseBtn  = document.getElementById('lb-close');

  // X button → close lightbox
  lbCloseBtn.addEventListener('click', closeLightbox);

  // Click on the dark background (not the image) → close lightbox
  lightbox.addEventListener('click', e => {
    if (e.target === lightbox) closeLightbox();
  });

  // Escape key → close lightbox
  document.addEventListener('keydown', e => {
    if (e.key === 'Escape') closeLightbox();
  });

  function openLightbox(type, src, title) {
    if (type === 'image') {
      lbImg.src             = src;
      lbImg.style.display   = 'block';
      lbVideo.style.display = 'none';
    } else {
      lbVideo.src            = src;
      lbVideo.style.display  = 'block';
      lbImg.style.display    = 'none';
    }
    if (lbCaption) lbCaption.textContent = title || '';
    lightbox.classList.add('open');
    document.body.style.overflow = 'hidden'; // prevent background scroll
  }

  function closeLightbox() {
    lightbox.classList.remove('open');
    lbVideo.pause();
    document.body.style.overflow = ''; // restore scroll
  }


  // ════════════════════════════════════════════════════════════════
  //  SCROLL REVEAL — fades in cards as you scroll down
  // ════════════════════════════════════════════════════════════════

  // IntersectionObserver watches elements and fires when they enter the viewport.
  // We use it to add the "visible" class which triggers the CSS fade-in.
  function observeReveal() {
    const observer = new IntersectionObserver((entries) => {
      entries.forEach((entry, index) => {
        if (entry.isIntersecting) {
          // Stagger the animation: each card delays slightly more than the last
          // So they fade in one after another rather than all at once
          setTimeout(() => {
            entry.target.classList.add('visible');
          }, index * 60); // 60ms stagger between each card

          // Stop watching this element once it's visible
          // (no point watching something that's already faded in)
          observer.unobserve(entry.target);
        }
      });
    }, {
      threshold: 0.08 // trigger when 8% of the element is visible
    });

    // Watch all elements with the "reveal" class that aren't already visible
    document.querySelectorAll('.reveal:not(.visible)').forEach(el => {
      observer.observe(el);
    });
  }

  // Run reveal on page load for any elements already on screen
  observeReveal();


  // ════════════════════════════════════════════════════════════════
  //  HAMBURGER MENU — mobile navigation
  //  Tap the ≡ icon on mobile to open/close the nav links.
  // ════════════════════════════════════════════════════════════════

  const hamburgerBtn = document.getElementById('hamburger');
  const navLinksList = document.getElementById('nav-links');

  if (hamburgerBtn) {
    // Toggle open/closed when the ≡ button is tapped
    hamburgerBtn.addEventListener('click', () => {
      hamburgerBtn.classList.toggle('open');
      navLinksList.classList.toggle('open');
    });

    // Close the menu when any nav link is tapped
    // (otherwise the menu stays open after navigating)
    navLinksList.querySelectorAll('a').forEach(link => {
      link.addEventListener('click', () => {
        hamburgerBtn.classList.remove('open');
        navLinksList.classList.remove('open');
      });
    });
  }


  // ════════════════════════════════════════════════════════════════
  //  BACK TO TOP BUTTON
  //  Appears in the bottom-right corner after scrolling 500px.
  //  Click it to smoothly scroll back to the top.
  // ════════════════════════════════════════════════════════════════

  const backToTopBtn = document.getElementById('back-to-top');

  window.addEventListener('scroll', () => {
    // Show the button when the user has scrolled more than 500px
    backToTopBtn.classList.toggle('visible', window.scrollY > 500);
  });

  backToTopBtn.addEventListener('click', () => {
    window.scrollTo({ top: 0, behavior: 'smooth' });
  });


}); // end DOMContentLoaded
